model_name: 'Unet'
load_model: False
use_gpu: True
output_root: './'
result_file_name: 'trainUnet'
data_dir: './data/image_toy'
n_class: 5
max_time: 3
lr: 0.00001
batch_size: 32
max_epoch: 3
weight_decay: 0.0001
lr_reduce_factor: 0.9
lr_schedule_patience: 10